fix: disabled edit/create profile form validation on change
nerdbord/good-dev-hunting-app pull request #102
Opened 2023-12-13 20:49 UTC by wawrzonnn

2023-12-14 09:52 UTC, Sumick requested changes
We should not disable validation completely, it should work after first submission try

2023-12-14 09:52 UTC, Sumick commented on src/components/CreateProfileForm/CreateProfileFormWrapper.tsx
> +      validateOnChange={false}
**issue:** You disabled live validation completely now - it should validateOnBlur, and validateOnChange but only when form is submitted once - we should use `touched` property to manage that in inputs

2023-12-14 12:36 UTC, AniaPiWo approved these changes

2023-12-15 19:23 UTC, hansac91 approved these changes

2023-12-15 19:38 UTC, mmcode9407 approved these changes

2023-12-16 21:40 UTC, Sumick requested changes
Mostly looks good, but let's do a little cleanup before merging - especially let's remove all`touched` from inputs level, and leave just error message

2023-12-16 21:40 UTC, Sumick commented on app/(profiles)/my-profile/create/page.tsx
> +  //   redirect(AppRoutes.myProfile)
**nitpick:** Comment to remove?

2023-12-16 21:40 UTC, Sumick commented on src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
> +          <InputFormError error={errors.city} touched={touched.city}>
**nitpick:** We don't need to pass `touched` here. You can just check it in `error field`, so it's:

```tsx
  <InputFormError error={touched.city && errors.city && errors.city}>
```

2023-12-16 21:40 UTC, Sumick commented on src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
> +        <InputFormError error={errors.remoteOnly} touched={touched.remoteOnly}>
**nitpick:** Same here

2023-12-16 21:40 UTC, Sumick commented on src/components/CreateProfile/PersonalInfo/PersonalInfo.tsx
> +          {touched.fullName && <span>huj</span>}
**issue:** xD To remove

2023-12-16 21:40 UTC, Sumick commented on src/components/InputFormError/InputFormError.tsx
> +      {error && touched && <p>{error}</p>}
**nitpick:** We don't need this prop here

2023-12-16 22:31 UTC, Sumick approved these changes
Goood job!

2023-12-16 22:36 UTC, merged