Fix/investigate session finding user logic
nerdbord/good-dev-hunting-app pull request #109
Opened 2023-12-17 16:19 UTC by szymonkadas

# Summary: 
- User with deleted account can't see nor edit other users profile data. Also user can now login to create account (clicking on createProfile also automatically creates account due to github authorization)
- finding user/profiles by user id's/email are now safekeeped from falsy values. where clause with falsy value returned first value from db. 
- profile pages and components are now also looking at session.user.id (probably) because of src/lib/auth.ts authOptions.callbacks jwt function that returned object with id null. Object that is indeed defined, so hence not falsy.

# Notes:
Problem has probably occurred mainly due to "if" conditions not enough strict for actual data behaviour, and tricky prisma findFirst functionality (undefined values would prove to unexpected behaviours).

2023-12-17 20:50 UTC, wawrzonnn approved these changes

2023-12-19 12:44 UTC, mmcode9407 approved these changes
Looks good! :)

2023-12-19 14:39 UTC, Sumick requested changes
Instead of changing so many things here, we should be able to make it from one place. Maybe just let's return null instead of an object with id of null? Then you would not have to change other things and add more checks
<img width="705" alt="Zrzut ekranu 2023-12-19 o 15 38 54" src="https://github.com/nerdbord/good-dev-hunting-app/assets/22893188/d93cf286-11b3-4d9d-ab6a-418d314edde7">

2023-12-19 14:39 UTC, Sumick commented on src/backend/user/user.service.ts
> +  if (!id) {
**nitpick:** We should not need that, as `id` is required

2023-12-19 14:39 UTC, Sumick commented on src/backend/user/user.service.ts
> +    return null
**nitpick:** We should not need that, as `email` is required

2023-12-19 14:39 UTC, Sumick commented on src/components/CreateProfileBtn/CreateProfileBtn.tsx
> +    if (!session?.user?.id) {
**nitpick:** We should leave as it is, and make session null if it's not present

2023-12-19 14:39 UTC, Sumick commented on src/components/Headers/AppHeader/AppHeader.tsx
> +  if (session?.user?.id) {
**nitpick:** We should leave as it is, and make session null if it's not present

2023-12-20 12:07 UTC, szymonkadas commented
Closing due to too many conflicts from changes from the meantime.

2023-12-20 12:07 UTC, closed without merging