Fix/tech stack component
nerdbord/good-dev-hunting-app pull request #110
Opened 2023-12-17 21:52 UTC by hansac91

2023-12-17 22:04 UTC, wawrzonnn approved these changes

2023-12-17 22:04 UTC, wawrzonnn commented on src/data/frontend/technologies/data.ts
> +  'Pandas',
where is obsługa dystrybutora lpg ?

2023-12-17 22:17 UTC, wawrzonnn requested changes
![hania](https://github.com/nerdbord/good-dev-hunting-app/assets/104648914/c35cb601-0dfa-4f6e-a4bc-c467fcd313fa)

gap: 10px nigga pls

2023-12-17 22:17 UTC, wawrzonnn commented on src/components/TechStackInput/TechStackInput.module.scss
> +  span {
font too big

2023-12-17 22:54 UTC, wawrzonnn approved these changes

2023-12-18 16:19 UTC, AniaPiWo approved these changes

2023-12-18 19:03 UTC, szymonkadas approved these changes
Looks good.

2023-12-19 09:29 UTC, mmcode9407 approved these changes
GJ!
Please, change props on camelCase in svg element before merging :)

2023-12-19 14:42 UTC, Sumick approved these changes
Good job! Im leaving 3 cleanup type comments

2023-12-19 14:42 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +      setFieldValue('techStack', [...values.techStack, tech])
**nitpick:** We already have field names in some enum, let's reuse it

2023-12-19 14:42 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +        'techStack',
**nitpick:** We already have field names in some enum, let's reuse it

2023-12-19 14:42 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformations.module.scss
> +  // margin-top: 20px;
**nitpick:** Comment to remove

2023-12-22 23:33 UTC, merged