Feat/landing navbar herosec
nerdbord/good-dev-hunting-app pull request #129
Opened 2024-01-11 22:01 UTC by hansac91

2024-01-11 22:24 UTC, wawrzonnn approved these changes

2024-01-11 22:28 UTC, Sumick requested changes
Mostly looks good! Few changes to implement:

- [ ] Fonts dont load properly. You can preview your deployment here: https://good-dev-hunting-app-git-feat-landing-navbar-herosec-nerdbord.vercel.app/
<img width="1343" alt="Zrzut ekranu 2024-01-11 o 23 28 12" src="https://github.com/nerdbord/good-dev-hunting-app/assets/22893188/19eb6f65-6567-4ba5-9e0d-3ad28a9fd36f">

- [ ] Find talents button does not work. it should redirect to `/profiles` where all profiles live
- [ ] let's move out landing `page.tsx` from `(profiles)` dir, and put it in root `./app`

2024-01-11 22:28 UTC, Sumick commented on app/(profiles)/page.tsx
**nitpick:** We should extract this page from our `(profiles)` directory, as landing is not part of profiles anymore

2024-01-12 11:40 UTC, szymonkadas approved these changes

2024-01-14 13:07 UTC, Sumick requested changes
Few changes to implement:

- [ ] Landing container broke 
<img width="1427" alt="Zrzut ekranu 2024-01-14 o 14 06 03" src="https://github.com/nerdbord/good-dev-hunting-app/assets/22893188/b2c514bb-31fe-4060-a53d-8840484bc3ad">

- [ ] Fonts still don't load properly
- [x] we should not show Find talents button in header when we are currently in `/profiles` route
- [ ] we should not duplicate `profiles` directory but change existing directory name from `(profiles)` to `profiles`

2024-01-14 13:07 UTC, Sumick commented on app/(profiles)/profiles/page.tsx
**nitpick:** No need to duplicate this `profiles` directory. Let's just change `(profiles)` to `profiles`, and move this `page.tsx` together with `page.module.scss`

2024-01-14 13:07 UTC, Sumick commented on app/page.tsx
> +  const cx = classNames.bind(styles)
**nit:** Let's move out `cx` out of component body (outside const)

2024-01-14 13:07 UTC, Sumick commented on src/components/FindTalentsBtn/FindTalentsBtn.tsx
> +
**nitpick:** Let's return null if current route is `AppRoute.profiles`, so it does not show when we are currently at this route

2024-01-14 17:52 UTC, hansac91 commented
Here's my reply:

>  Fonts dont load properly. You can preview your deployment here: https://good-dev-hunting-app-git-feat-landing-navbar-herosec-nerdbord.vercel.app/

I checked the link above and on localhost and everything is okay. 

> * [ ]  Find talents button does not work. it should redirect to `/profiles` where all profiles live - fixed

2024-01-15 10:28 UTC, Sumick approved these changes
👌 Let's remove `yarn.lock` before merging, so you don't have this conflict

2024-01-15 10:57 UTC, merged