Refactor/tech as separate model
nerdbord/good-dev-hunting-app pull request #154
Opened 2024-01-23 19:38 UTC by szymonkadas

# Summary:
- changed profile.techStack in db so it would be easier to work with it.
- updated all code already related to techStack, especially profile updating chunks.

# Caveats: 
- this is not yet ready to merge code for sure, there's many aspects to discuss, some of them were mentioned in the comments (in code). Request for comments.
- code is yet to be optimised, would love some suggestions  
- not sure if every change was made in good direction, request for comments!
- changes from the meantime haven't been merged, there was already too much code to change already and to wrap my head around, so i'll handle that in next iterations of this pr, hence i'm merging it to my other task that changes are existent in this pr (so they won't be visible).

2024-01-23 19:48 UTC, szymonkadas commented
Oh and please, i would mostly love suggestions about updating user with tech stack!

2024-01-24 10:07 UTC, szymonkadas commented on prisma/schema.prisma
> +  name        String                 @unique
forgot about @id, name would serve as an id for simplicity

2024-01-24 10:09 UTC, szymonkadas commented on src/components/Filters/Filters.tsx
> +  const handleSelectMulti = (
changes from other branch, (implementing multi-select on seniority/tech etc)

2024-01-24 13:04 UTC, Sumick requested changes
Let's simplify it first, and I will do another review round:

- [ ] Let's simplify DB schema, so we add only one new model which is `Technology`. Let's remove `TechnologyOnProfile` as it adds not necessary layer of complexity. `Technology` model should look like following:
```ts
model Technology {
  id               String.               @default(uuid())
  name        String                 @unique
  profiles     Profile[]
}
```
Then Profile model should be:
```
model Profile {
  // ... all previous fields
  techStack:  Technology[]
}
```

- [ ] Let's keep `ProfileModel` name instead of changing it to `ProfileModelSimplified` as it's not domain related change
- [ ] When user updates techStack in Profile it should create new Technology if it does not exists or if it exists it should connect to existing one
- [ ] We should type reusable includes object using Prisma.validator
- [x] We should not delete Technologies when removing them from Profile, but we should disconnect them from Profile leaving them in database, so other Profile can connect to it

2024-01-24 13:08 UTC, szymonkadas commented on src/backend/profile/profile.service.ts
> +    await prisma.technologyOnProfile.deleteMany({
It's actually removing relationship not the technology itself

2024-01-24 23:11 UTC, szymonkadas commented
Didn't type include object, typed objects obtained from prisma calls using this include object.

2024-01-25 11:01 UTC, szymonkadas commented on src/backend/profile/profile.service.ts
> +export async function upsertTechnology(techName: string) {
To be deleted.

2024-01-25 19:59 UTC, szymonkadas commented
Ready for 2nd round, need to merge changes from the meantime.

2024-01-26 13:43 UTC, Sumick approved these changes
I will merge now this PR into my & Ania's PR as well as second Szymon PR as we all have changes related to filter logic, and there are tons of conflicts. It will be easier to fix it on one branch

2024-01-26 13:43 UTC, merged