fix: [dev-profile] Mobile / Header objects alignment to the left
nerdbord/good-dev-hunting-app pull request #159
Opened 2024-01-25 21:33 UTC by Adriann77

2024-01-25 21:55 UTC, mr-fox93 approved these changes
good job, checked on my phone.

2024-01-25 22:52 UTC, hansac91 approved these changes

2024-01-26 08:53 UTC, mmcode9407 requested changes
Looks good, but we have to fix some styles yet :)

2024-01-26 08:53 UTC, mmcode9407 commented on src/components/Headers/UserProfileHeader/UserProfileHeader.module.scss
> -  justify-content: flex-end;
We style according to the desktop first rule. So move it to the `@include mobile` mixin. The `flex-end` value should stay for divs without `withBackButtonClass` for the desktop.

2024-01-26 08:53 UTC, mmcode9407 commented on src/components/Headers/UserProfileHeader/UserProfileHeader.module.scss
> -  justify-content: space-between;
The same as above. Desktop first, and then add `@include Mobile` with some styles for mobile :)

2024-01-26 08:53 UTC, mmcode9407 commented on src/components/Headers/UserProfileHeader/UserProfileHeader.module.scss
> +@media (min-width: 768px) {
When you use the `@include Mobile` mixin with `withBackButton` class, you won't need this rule anymore.

2024-01-29 12:20 UTC, Sumick approved these changes

2024-01-29 20:51 UTC, mmcode9407 approved these changes

2024-02-02 20:10 UTC, merged