feat: team members are now listed on meet our team, todo: figure out …
nerdbord/good-dev-hunting-app pull request #172
Opened 2024-02-01 12:23 UTC by szymonkadas

# Summary:
team members are visible in meet our team

### Caveats:
- I'm not so sure if the way i rendered out meet our team is good enough,
- should vertical card even allow placeholder data?  Should it only display ONLY Team members, and if they're not existent display NOTHING? 

### TODO: 
figure out how to display availability (dots, etc)

2024-02-01 14:57 UTC, Sumick requested changes
We need to improve it as it is implemented incorrectly - I've posted solution in comment

2024-02-01 14:57 UTC, Sumick commented on src/actions/team/fetchTeam.tsx
> +export async function fetchTeam() {
**nit:** Actions are for POSTS, we don't have to keep them here, as you can just use `getTeamProfiles` directly in server component

2024-02-01 14:57 UTC, Sumick commented on src/components/landing-page/MeetTeam/MeetTeam.tsx
> +    if (teamData.length > 0) {
**issue:** This is super complicated, and you created `server action` to run it on the client which makes no sense. It should look like following (remember to remove `use client` directive). Don't worry about scenario when there are no records. There will always be some records

```tsx
const MeetTeam = async () => {
  const teamProfiles = await getTeamProfiles();

  // Calculate midpoint differently to ensure one half has at least 4 items
  let midpoint;
  if (teamProfiles.length < 8) {
    // Ensure the first half has at least 4 items, if total less than 8
    midpoint = 4;
  } else {
    // Standard calculation if enough items for both halves to have at least 4
    midpoint = Math.ceil(teamProfiles.length / 2);
  }

  const firstHalfProfiles = teamProfiles.slice(0, midpoint);
  const secondHalfProfiles = teamProfiles.slice(midpoint);

  return (
    <section id="MeetTeam" className={styles.wrapper}>
      <div className={styles.titleBox}>
        <p className={styles.sectionName}>WORKING AS A TEAM</p>
        <h2 className={styles.title}>Meet our team</h2>
        <h5 className={styles.subtitle}>Meet passionates behind the scene</h5>
      </div>
      <div className={styles.cardsWrapper}>
        <div className={styles.slider}>
          <div className={styles.cardsBox}>
            {firstHalfProfiles.map(profile => <VerticalCard {...profile} />)}
          </div>
        </div>
        {!!secondHalfProfiles.length && <div className={styles.slider}>
          <div className={styles.cardsBox}>
            {secondHalfProfiles.map(profile => <VerticalCard {...profile} />)}
          </div>
        </div>}
      </div>
    </section>
  );
};

```

2024-02-01 21:45 UTC, Sumick approved these changes
Looks good!

2024-02-01 22:13 UTC, mmcode9407 approved these changes

2024-02-02 19:45 UTC, hansac91 approved these changes

2024-02-02 20:05 UTC, merged