Feat/filters dropdown
nerdbord/good-dev-hunting-app pull request #18
Opened 2023-06-17 18:36 UTC by AniaPiWo

2023-06-17 18:47 UTC, wawrzonnn approved these changes

2023-06-18 21:13 UTC, Sumick requested changes
Overall looks good! I think we are missing one thing here - two very specific props, that are currently missing in this `FilterButton` component. In your current implementation, you won't be able to set value in that `FilterButton` in other place than this component body. You should be able to set all these selected values in one place - which is probably `Filters` component.

2023-06-18 21:13 UTC, Sumick commented on src/components/FilterButton/FilterButton.tsx
> +            <form className={styles.dropdownForm}>
**question:** Why `form` here?

2023-06-21 16:57 UTC, Sumick approved these changes
Approving, but please do simplify this filter logic, as in my example below. Let's also add enum for filter names, to keep them standarized

2023-06-21 16:57 UTC, Sumick commented on src/components/Filters/Filters.tsx
> +      case 'Availability':
**nitpick:** You could keep these values as enum, it's quite important, and we will avoid string duplication / maintanance:

```ts
export enum FilterNames {
Availability = "Availability",
...
}

2023-06-21 16:57 UTC, Sumick commented on src/components/Filters/Filters.tsx
> +          onSelect={(option) => handleSelect(option, 'Technology')}
**nitpick:** Then you could use this enum from above here: 

```tsx
  onSelect={(option) => handleSelect(option, FilterNames.Technology)}
```

2023-06-21 17:19 UTC, merged