Feat/patch-profile-route
nerdbord/good-dev-hunting-app pull request #19
Opened 2023-06-18 17:54 UTC by DanielSzczucki

2023-06-18 17:56 UTC, NerdbordMentor approved these changes
## Code Review Report

### app/api/profiles/[id]/route.ts
- The `updateUserData` function is imported correctly.
- The `PATCH` endpoint is implemented correctly.
- The `userDataToUpdate` is obtained from the request body using `request.json()`.
- The `updateUserData` function is called with the `id` and `userDataToUpdate`.
- The response is returned as JSON with a success message and the updated profile.
- Errors are caught and returned as a NextResponse with the error message.

### src/backend/profile/profile.service.ts
- The `UpdateProfilePayload` type is imported correctly.
- The `City` and `Country` types are imported correctly.
- The `updateUserCity` function is added to update the user's city.
- The `updateUserCountry` function is added to update the user's country.
- The `updateUserData` function is implemented to update the user's data.
- The old and new city and country values are obtained for comparison.
- If the new city or country is different from the old value, the corresponding update function is called.
- The profile is updated with the new data using `prisma.profile.update`.
- The user's email is also updated using `prisma.user.update`.
- The updated profile is returned.

### src/backend/profile/profile.types.ts
- The `UpdateProfilePayload` type is added correctly as a partial of `ProfilePayload`.

### tsconfig.json
- The `utills` directory is added to the include section.

### utills/dbMockup.ts
- The correct import statement for `Profile` is used.

Overall, the code changes seem to align with the task requirements. The implementation of the PATCH endpoint in `app/api/profiles/[id]/route.ts` allows for updating an existing profile for the logged-in user using Prisma client. The `updateUserData` function in `src/backend/profile/profile.service.ts` handles the logic for updating the user's data, including the city and country. The code changes in `src/backend/profile/profile.types.ts`, `tsconfig.json`, and `utills/dbMockup.ts` are minor and do not affect the functionality of the code.

However, there are a few suggestions for improvement:
- It would be beneficial to add validation and error handling for the payload received in the PATCH endpoint.
- Consider adding proper error handling and response codes for different scenarios, such as when the user or profile is not found.

Please let me know if you have any questions or if there's anything else I can assist you with.

2023-06-18 21:35 UTC, Sumick requested changes
I found few improvements we could implement here

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +    const foundCity = await prisma.city.findFirst({
**nitpick:** This update should not be dependent on found city, because if such city does not exist, it should be created

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +    const foundCountry = await prisma.country.findFirst({
**nitpick**: This update should not be dependent on found country, because if such city does not exist, it should be created

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +  await prisma.profile.update({
**nitpick:** We should `return` this update result

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +  return getProfileById(id)
**nitpick:** And then we could remove this additional query

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +  if (!newCountry) return
**nitpick:** We should not do such `if` without throwing any error. However we should remove this if and always allow user to update country

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +        connectOrCreate: {
**nitpick:** Instead of `connectOrCreate`, use `upsert`, so it will update record if found, or create if does not exist

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +  await prisma.profile.update({
**nitpick:** Instead of `connectOrCreate`, use `upsert`, so it will update record if found, or create if does not exist

2023-06-18 21:35 UTC, Sumick commented on src/backend/profile/profile.service.ts
> +  if (!newCity) return
**nitpick**: We should not do such if without throwing any error. However we should remove this if and always allow user to update city

2023-06-20 05:37 UTC, NerdbordMentor approved these changes
## Code Review Report

### app/api/profiles/[id]/route.ts
- The `updateUserData` function is imported correctly.
- The `PATCH` endpoint is implemented correctly.
- The `userDataToUpdate` is parsed from the request body correctly.
- The `updateUserData` function is called correctly with the `id` and `userDataToUpdate`.
- The response is returned correctly with a success message and the updated user profile.
- Error handling is implemented correctly, returning an error response if an error occurs.

### src/backend/profile/profile.service.ts
- The `UpdateProfilePayload` type is imported correctly.
- Two new helper functions, `updateUserCity` and `updateUserCountry`, are added to update the city and country data respectively.
- The `updateUserData` function is implemented correctly.
- The `newCity` and `newCountry` variables are extracted from the `userDataToUpdate`.
- The `updateUserCity` and `updateUserCountry` functions are called correctly with the `id` and respective new data.
- The user profile is updated correctly using the `prisma.profile.update` method.
- The updated user profile is returned.

### src/backend/profile/profile.types.ts
- The `UpdateProfilePayload` type is added correctly as a partial of `ProfilePayload`.

### tsconfig.json
- The `utills` directory is added to the include section correctly.

### utills/dbMockup.ts
- The unnecessary imports for `City`, `Country`, and `User` are removed correctly.

Overall, the code changes seem to align with the task requirements. The implementation of the endpoint for updating profile data using Prisma client looks good. The code follows best practices and handles errors appropriately. Well done!

If you have any further questions or need additional assistance, feel free to ask.

2023-06-21 10:53 UTC, AniaPiWo approved these changes

2023-06-21 10:54 UTC, merged