Feat/implement GitHub authorization
nerdbord/good-dev-hunting-app pull request #20
Opened 2023-06-21 16:35 UTC by AniaPiWo

2023-06-21 16:36 UTC, NerdbordMentor approved these changes
## Code Review Report

### app/api/auth/[...nextauth]/route.js
- The code for importing `NextAuth` and `GithubProvider` is correct.
- The `authOptions` object is correctly defined with the `providers` array.
- The `clientId` and `clientSecret` are correctly passed as environment variables.

### app/layout.tsx
- The import statement for `AuthProvider` is correct.
- The `AuthProvider` component is correctly wrapped around the `Header` and `div` components.
- This change ensures that the authentication provider is available to the entire application.

### next.config.js
- The environment variables `GIHUB_ID` and `GIHUB_SECRET` are correctly defined.

### package.json
- The `next-auth` package has been added as a dependency.
- The `prisma` package has been moved to the devDependencies section.

### src/components/AuthProvider/AuthProvider.tsx
- The import statements for `React` and `SessionProvider` are correct.
- The `AuthProvider` component is correctly defined as a functional component.
- The `children` prop is correctly typed as `ReactNode`.
- The `SessionProvider` component is correctly used to wrap the children.

### tsconfig.json
- The include section has been updated to include `.next/types/**/*.ts`.
- This change ensures that the generated Next.js types are included in the TypeScript compilation.

Overall, the code changes align with the task requirements of implementing Github authorization using NextAuth. The necessary packages and components have been added, and the environment variables are correctly used. The code changes also follow best practices by using functional components and properly wrapping components with providers.

Please let me know if you have any specific questions or if there's anything else I can assist you with.

2023-06-21 16:40 UTC, Sumick requested changes
Authorizing with Github should create new user if one does not exist. You should fill `GitHubDetails` model with fetched data from authorization

2023-06-24 17:31 UTC, wawrzonnn approved these changes

2023-06-24 17:31 UTC, Sumick approved these changes

2023-06-25 11:09 UTC, merged