feat: create profile list UI - first attempt
nerdbord/good-dev-hunting-app pull request #21
Opened 2023-06-23 20:17 UTC by hansac91

2023-06-23 20:18 UTC, hansac91 commented
I need a tip how to solve img upload. Right now I just added it as a file to my branch and imported. Should I include it somehow in ProfileData.tsx? Or maybe create another file using Image component according to next.js documentation? if so, what should I include in src?

2023-06-27 16:38 UTC, NerdbordMentor approved these changes
## Code Review Report

### app/page.tsx
- No issues found. The code change adds the `ProfileList` component to the `Home` component.

### src/assets/images/ProfilePicture.png
- No issues found. The code change adds the `ProfilePicture.png` image.

### src/components/ProfileList/ProfileData.tsx
- No issues found. The code change adds an array of profile data.

### src/components/ProfileList/ProfileList.module.scss
- No issues found. The code change adds SCSS styles for the `ProfileList` component.

### src/components/ProfileList/ProfileList.tsx
- No issues found. The code change implements the `ProfileList` component according to the task requirements.
- The component renders a list of profile cards based on the `ProfileData` array.
- Each profile card displays the profile picture, name, seniority, location, and technologies.
- The `TechnologyChip` component is used to render the technology badges with appropriate styling based on the seniority and theme.
- The component handles different job specializations (Frontend, Backend, Fullstack) and assigns appropriate styles to the seniority and technology badges.
- The component also includes a title for the list of profiles.

Overall, the code changes seem to meet the requirements of creating a profiles list with engineer profile cards. The UI implementation closely matches the provided design, and the list handles both empty and non-empty states. Well done!

2023-06-27 16:58 UTC, Sumick requested changes
Looks good - we need mainy to add React way of using logic in component. Using `useState`, and `useEffect` are the most important, and the most commonly used react hooks for handling logic.

2023-06-27 16:58 UTC, Sumick commented on src/components/ProfileList/ProfileList.tsx
> +    return styles.backend
**nitpick:** We should split it into 2 separate functions, like: `getTechnologyClassByTheme`, and `getTechnologyClassBySeniority`, so they handle one argument

2023-06-27 16:58 UTC, Sumick commented on src/components/ProfileList/ProfileList.tsx
> +  let theme: JobSpecialization
**nitpick:** We should use `useState` here for keeping, and updating such value: 
```
const [theme, setTheme] = useState(null)
```

2023-06-27 16:58 UTC, Sumick commented on src/components/ProfileList/ProfileList.tsx
> +    theme = JobSpecialization.Backend
**nitpick:** Then this should be set using `useEffect`, so it's:

```tsx
useEffect(() => {
 if (data.seniority.includes('Frontend')) {
    setTheme(JobSpecialization.Frontend)
 ...
}, [])
```

2023-06-27 16:58 UTC, Sumick commented on src/components/ProfileList/ProfileList.tsx
> +        {ProfileData.map((profile) => (
**nitpick:** variable names in javascript should be written in `camelCase`

2023-07-09 18:20 UTC, wawrzonnn approved these changes

2023-07-10 11:59 UTC, Sumick approved these changes
Looks nice, good job Hania!

2023-07-10 17:40 UTC, merged