Feat/create profile header UI
nerdbord/good-dev-hunting-app pull request #24
Opened 2023-06-27 14:10 UTC by AniaPiWo

2023-06-27 14:10 UTC, NerdbordMentor approved these changes
## Code Review

Overall, the code changes look good and align with the task requirements. Here are some specific feedback and suggestions:

### app/my-profile/page.module.scss
- The styles in this file look good. They match the design provided in the task requirements.

### app/my-profile/page.tsx
- The changes in this file look good. The `ProfileMain` component and `LogOutBtn` component are imported and rendered correctly.

### next.config.js
- The addition of the `images` configuration in `next.config.js` looks good. It specifies the domains where images are hosted.

### public/default-avatar.png
- The addition of the `default-avatar.png` image looks good. It provides a default avatar image for users who don't have a profile picture.

### src/assets/icons/CopyEmail.tsx
- The implementation of the `CopyEmail` icon component looks good. It renders an SVG icon for copying email.

### src/assets/icons/GithubIcon2.tsx
- The implementation of the `GithubIcon2` icon component looks good. It renders an SVG icon for GitHub.

### src/assets/icons/LinkedIn.tsx
- The implementation of the `LinkedIn` icon component looks good. It renders an SVG icon for LinkedIn.

### src/assets/icons/PolandFlag.tsx
- The implementation of the `PolandFlag` icon component looks good. It renders an SVG icon for the Poland flag.

### src/components/LogOutBtn/LogOutBtn.tsx
- The implementation of the `LogOutBtn` component looks good. It renders a button for logging out using the `signOut` function from `next-auth/react`.

### src/components/ProfileMain/ProfileMain.module.scss
- The styles in this file look good. They match the design provided in the task requirements.

### src/components/ProfileMain/ProfileMain.tsx
- The implementation of the `ProfileMain` component looks good. It renders the profile header UI based on the provided design.
- The user's avatar, name, location, and additional information are displayed correctly.
- The social icons for GitHub, LinkedIn, and copying email are rendered correctly.
- The `LogOutBtn` component is imported and rendered correctly.

Overall, the code changes meet the requirements of creating the profile header UI based on the provided design. The code follows best practices and is well-structured. Great job!

2023-06-27 16:20 UTC, Sumick requested changes
Looks good! We need to put this Profile into layout component we discussed yesterday + replace this base64 icon with normal image

2023-06-28 17:38 UTC, wawrzonnn approved these changes

2023-06-28 17:38 UTC, Sumick approved these changes
🙌

2023-06-28 17:39 UTC, merged