Feat/move GitHub stars button component
nerdbord/good-dev-hunting-app pull request #258
Opened 2024-03-10 19:43 UTC by SzDabrowski

2024-03-10 19:45 UTC, wawrzonnn approved these changes

2024-03-11 21:42 UTC, Sumick requested changes
Spacing between logo, and Github Stars is incorrect (they are too close) + it is still on the right side in homepage:
<img width="417" alt="Zrzut ekranu 2024-03-11 o 22 41 30" src="https://github.com/nerdbord/good-dev-hunting-app/assets/22893188/e1d8433d-d97e-4207-95f6-21ab3939ed63">
<img width="1290" alt="Zrzut ekranu 2024-03-11 o 22 41 51" src="https://github.com/nerdbord/good-dev-hunting-app/assets/22893188/ed3708aa-8bd4-4fca-ba29-d06c85975568">

2024-03-13 16:08 UTC, wawrzonnn approved these changes

2024-03-13 16:10 UTC, hansac91 approved these changes

2024-03-13 16:12 UTC, merged