Feat/create personal information section UI
nerdbord/good-dev-hunting-app pull request #26
Opened 2023-07-02 11:59 UTC by AniaPiWo

2023-07-02 12:00 UTC, NerdbordMentor approved these changes
## Code Review Report

### app/(profile)/create-profile/page.module.scss
- The changes in this file look good.
- The new styles for `.main`, `.titleBox`, `.saveProfileBtn`, and `.formBox` are implemented correctly.
- The styles are consistent with the provided design.

### app/(profile)/create-profile/page.tsx
- The changes in this file look good.
- The `PersonalInfo` component is imported correctly.
- The `CreateProfilePage` component is updated to include the new UI elements.
- The styles from `page.module.scss` are applied correctly to the elements.

### src/assets/icons/ImportantIcon.tsx
- The new `ImportantIcon` component looks good.
- It renders an SVG icon with the correct dimensions and paths.
- The icon is filled with the appropriate color.

### src/components/PersonalInfo/PersonalInfo.jsx
- The new `PersonalInfo` component looks good.
- It renders a container with two sections: `.left` and `.right`.
- The text and input fields are implemented correctly.
- The `ImportantIcon` component is used correctly for the "Contact email" and "Bio" fields.

### src/components/PersonalInfo/PersonalInfo.module.scss
- The new styles for `.container`, `.left`, `.personalInfo`, `.right`, `.formTitle`, `.formInput`, `.formTextarea`, `.formItem`, and `.lettersCount` are implemented correctly.
- The styles are consistent with the provided design.

Overall, the code changes meet the requirements of creating the "Personal Information" section in the "Create a profile" page. The UI is implemented as close as possible to the provided design. The new components and styles are integrated correctly into the existing codebase.

Great job on implementing the changes! Let me know if you have any questions or need further assistance.

2023-07-02 15:21 UTC, wawrzonnn approved these changes

2023-07-02 19:31 UTC, hansac91 approved these changes

2023-07-02 20:47 UTC, Sumick requested changes
Buttons, and inputs should be separate components. Just like in Nerdux UI

2023-07-02 20:47 UTC, Sumick commented on src/components/PersonalInfo/PersonalInfo.jsx
> +          <input
**nitpick:** Inputs should be separate components

2023-07-02 20:47 UTC, Sumick commented on app/(profile)/create-profile/page.tsx
> +        <button className={styles.saveProfileBtn}>
**issue:** Button should be separate component. Try to think of it as you would do Nerdux UI system

2023-07-04 16:15 UTC, Sumick requested changes
Components are missing `interfaces`, and some props + input component should be more generic, just as in Nerdux. We should standardize it the same way, as in design system.

2023-07-04 16:15 UTC, Sumick commented on src/components/CreateProfile/CreateProfileInput/CreateProfileInput.jsx
> +const CreateProfileInput = ({ placeholder }) => {
**nitpick:** This component should be more generic, like `TextInput` -  we are also missing required props here, like `onChange`, `value`. Exactly how you would do it in Nerdux

2023-07-04 16:15 UTC, Sumick commented on src/components/CreateProfile/CreateProfileTextArea/CreateProfileTextArea.jsx
> +const CreateProfileTextArea = ({ placeholder }) => {
**nitpick:** Same here - why `CreateProfileTextArea` if it's a generic component. We are also missing props interface here

2023-07-05 17:02 UTC, Sumick approved these changes
Looks much better:) Good job!

2023-07-05 17:04 UTC, merged