Feat/create work information section UI
nerdbord/good-dev-hunting-app pull request #32
Opened 2023-07-08 14:54 UTC by AniaPiWo

2023-07-08 14:55 UTC, NerdbordMentor submitted a review, later dismissed
## Code Review Report

### Task goal
The task goal was to create a Work Information section in the Create a Profile page. The UI should be implemented as close as possible to the provided design.

### Code changes review

#### app/(profile)/create-profile/page.tsx
The WorkInformation component has been imported and added to the CreateProfilePage component. This change aligns with the task requirements.

#### src/components/CreateProfile/WorkInformation/WorkInformation.tsx
A new WorkInformation component has been created. It includes dropdowns for Position and Seniority, a text area for Tech Stack, and checkboxes for Employment Type. This aligns with the task requirements.

#### src/components/CreateProfile/WorkInformation/WorkInformations.module.scss
The corresponding styles for the WorkInformation component have been added. Without the design, it's hard to say if it matches exactly, but it seems to be in line with the task requirements.

#### src/components/Filters/Filters.tsx
The Filters component has been refactored to use a DropdownFilter component instead of a FilterButton component. This change doesn't seem to be directly related to the task requirements, but it doesn't contradict them either.

#### src/inputs/Dropdowns/DropdownBio/DropdownBio.tsx and src/inputs/Dropdowns/DropdownBio/DropdownBio.module.scss
A new DropdownBio component has been created. It seems to be a reusable dropdown component with a label, which could be used in the WorkInformation component. This aligns with the task requirements.

#### src/inputs/Dropdowns/DropdownFilter/DropdownFilter.tsx and src/inputs/Dropdowns/DropdownFilter/DropdownFilter.module.scss
The FilterButton component has been renamed to DropdownFilter and now includes a label. This change doesn't seem to be directly related to the task requirements, but it doesn't contradict them either.

#### Other changes
Other changes in files like app/(profile)/create-profile/page.module.scss, app/(profile)/my-profile/page.module.scss, app/globals.scss, src/components/Container/Container.module.scss, src/components/Container/Container.tsx, src/components/CreateProfile/PersonalInfo/PersonalInfo.tsx, and src/inputs/Switch/Switch.module.scss are minor formatting changes or unrelated to the task requirements.

### Conclusion
The code changes seem to cover the task requirements of creating a Work Information section in the Create a Profile page. However, without seeing the actual design or running the code, it's hard to say if the implementation matches the design exactly.

2023-07-08 15:31 UTC, wawrzonnn requested changes

2023-07-08 15:31 UTC, wawrzonnn commented on src/components/CreateProfile/WorkInformation/WorkInformations.module.scss
> +.lettersCount {
this class is duplicated

2023-07-08 15:31 UTC, wawrzonnn commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +    console.log(filters)
remove console.logs

2023-07-08 15:31 UTC, wawrzonnn commented on src/inputs/Dropdowns/DropdownBio/DropdownBio.tsx
> +                  className={`${styles.checkbox} ${
To dynamic classes, you should use the "bindclasses" library included in the project's documentation.

2023-07-09 18:01 UTC, wawrzonnn approved these changes

2023-07-10 12:06 UTC, Sumick requested changes
Looks good, but we need to do cleanup here before merging

2023-07-10 12:06 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +  const initialState = {
**nitpick:** We should move it out from component body, and type it properly (type object, don't do `as` something)

2023-07-10 12:06 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +  const filterLists = {
**nitpick:** Let's move it out from component body

2023-07-10 12:06 UTC, Sumick commented on src/components/CreateProfile/WorkInformation/WorkInformation.tsx
> +    console.log(filters)
**nitpick:** Log to remove

2023-07-10 12:06 UTC, Sumick commented on src/components/Filters/Filters.tsx
> +    technology: [] as string[],
**nitpick:** We should move it out from component body, and type it properly (type object, don't do `as` something)

2023-07-10 12:06 UTC, Sumick commented on src/components/Filters/Filters.tsx
> +      'Python',
**nitpick:** We should move it out from component body

2023-07-10 13:34 UTC, DanielSzczucki approved these changes

2023-07-10 13:43 UTC, merged