Feat/adding cookies banner
nerdbord/good-dev-hunting-app pull request #354
Opened 2024-11-13 12:28 UTC by transcendence12

- create cookies banner component,
- add cookies banner component to layout.tsx

2024-11-13 12:30 UTC, NerdbordMentor commented on apps/platform-app/src/app/[locale]/(profile)/(components)/CookieBanner/CookieBanner.module.scss
> +  // height: 322px;
**nitpick**: Consider removing the commented-out height property if it's not needed to keep the code clean.

2024-11-13 12:30 UTC, NerdbordMentor commented on apps/platform-app/src/app/[locale]/(profile)/(components)/CookieBanner/CookieBanner.module.scss
> +  @include mobile {
**suggestion**: Consider using a mixin or variable for the z-index value to maintain consistency across the application.

2024-11-13 12:30 UTC, NerdbordMentor commented on apps/platform-app/src/app/[locale]/(profile)/(components)/CookieBanner/CookieBanner.tsx
> +      const hasAcceptedCookies = localStorage.getItem('cookiesAccepted')
**issue**: Consider adding a check for localStorage availability to enhance compatibility with environments where localStorage is not available.

2024-11-13 12:30 UTC, NerdbordMentor commented on apps/platform-app/src/app/[locale]/(profile)/(components)/CookieBanner/CookieBanner.tsx
> +  if (!isBannerVisible) return null
**suggestion**: Consider using a more descriptive variable name for `isBannerVisible` to clarify its purpose, such as `isCookieBannerVisible`.

2024-11-13 12:30 UTC, NerdbordMentor approved these changes
## Overall Feedback

The implementation of the CookieBanner component meets the task requirements by providing a banner that allows users to accept cookies before using the page. The component is integrated into the layout and styled according to the provided Figma design. The use of localStorage to track cookie acceptance is a practical approach, and the error handling for localStorage access is a good practice.

### Things Missing:

- [] Ensure that the design matches the Figma design exactly, including any specific styling or layout details that may not be visible in the code provided.

### Things That Went Well:

- The CookieBanner component is well-structured and follows React best practices.
- The use of localStorage for managing cookie acceptance is efficient and straightforward.
- The styling is responsive and adapts well to different screen sizes.

2024-11-13 12:42 UTC, Sumick requested changes
Code looks great! However we need to implement few more things. Sorry that I haven't specified them before but I've just read about the proper approach in terms of cookie rejection.

1. The scenario when user rejects cookies. Then we should not track him using Google Analytics. I mean, GA tag should not be rendered.
2. If we want to conditionally render GA tag, we will need to have that information server side - so using localStorage as storage for cookie consent selection will not work, as it only works client side. Cookie banner could be server component in our implementation.

2024-11-18 09:35 UTC, transcendence12 commented
GA4 should collect traces of the user in consent mode. If the user accepts cookies, the information will be stored in the cookie. If the user does not consent ga4 will be active, but the user will not be associated with any identifier. In the developer tools under the network tab you should see `collect`

- create a Google Analytics component,
- add the GA component to the layout, 
- in the cookie banner, the consent information is stored in cookies (values: `granted` or `denied`),
- add privacy policy in the link form banner cookies,
- remove import from next third party google analytics (doesn't offer Consent Mode) and replace by custom component

2024-11-20 18:15 UTC, Sumick approved these changes
Amazing job!!! Congrats ❤️‍🔥 Let's just ensure if we need to remove google analytics package before merging and we are ready to go :)

2024-11-20 18:15 UTC, filwas approved these changes
Lookin' good!

2024-11-20 19:00 UTC, merged