Feat/profile form validation
nerdbord/good-dev-hunting-app pull request #36
Opened 2023-07-11 19:37 UTC by wawrzonnn

2023-07-11 19:38 UTC, NerdbordMentor approved these changes
## Code Review

Based on the provided code changes and the task requirements, here is my code review:

### app/(profile)/create-profile/page.tsx
- The `FormProvider` component from the `FormContext` is imported and wrapped around the existing JSX code.
- This change ensures that the form context is available to all child components within the `FormProvider`.

### app/api/auth/[...nextauth]/types.ts
- No changes were made to this file.

### package.json
- The `formik` package has been added as a dependency.

### src/assets/icons/ErrorIcon.tsx
- A new component `ErrorIcon` has been added to display an error icon.

### src/components/CreateProfile/CreateProfileHeader/CreateProfileHeader.module.scss
- Styles for error messages have been added.

### src/components/CreateProfile/CreateProfileHeader/CreateProfileHeader.tsx
- The `FormProvider` is imported from the `FormContext`.
- The `useFormContext` hook is imported from the `FormContext`.
- The `handleSubmit` and `errors` are extracted from the form context using the `useFormContext` hook.
- An error message is displayed at the top of the form if there are any errors present.
- The `handleButtonClick` function now calls the `handleSubmit` function instead of logging a message.

### src/components/CreateProfile/LocationPreferences/LocationPreferences.module.scss
- Styles for error messages have been added.

### src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
- The `useFormContext` hook is imported from the `FormContext`.
- The `values`, `handleChange`, and `errors` are extracted from the form context using the `useFormContext` hook.
- Error messages and styles have been added for each input field.
- The input values are now controlled by the form context values and handled by the form context's `handleChange` function.

### src/components/CreateProfile/PersonalInfo/PersonalInfo.module.scss
- Styles for error messages have been added.

### src/components/CreateProfile/PersonalInfo/PersonalInfo.tsx
- The `useFormContext` hook is imported from the `FormContext`.
- The `values`, `handleChange`, and `errors` are extracted from the form context using the `useFormContext` hook.
- Error messages and styles have been added for each input field.
- The input values are now controlled by the form context values and handled by the form context's `handleChange` function.

### src/components/CreateProfile/WorkInformation/WorkInformation.tsx
- The `useFormContext` hook is imported from the `FormContext`.
- The `values`, `handleChange`, and `errors` are extracted from the form context using the `useFormContext` hook.
- Error messages and styles have been added for each input field.
- The input values are now controlled by the form context values and handled by the form context's `handleChange` function.

### src/components/Headers/DefaultHeader/DefaultHeader.tsx
- The `data: session` destructuring has been removed from the `useSession` hook, as it is not used in the component.

### src/contexts/FormContext.tsx
- A new context called `FormContext` has been created using the `createContext` function.
- The `FormProvider` component has been created to provide the form context to its children.
- The `useFormContext` hook has been created to access the form context values and functions.
- The `validate` function has been added to validate the form values based on the task requirements.

### src/inputs/Checkbox/Checkbox.tsx
- The `onChange` function now receives the event object instead of a boolean value.
- The `name` prop has been added to the input element.

### src/inputs/Dropdowns/DropdownBio/DropdownBio.tsx
- The `name` prop has been added to the component.
- The `handleSelect` function has been modified to call the `onChange` function with the selected option.

### src/inputs/Switch/Switch.tsx
- The `onChange` function now receives the event object instead of a boolean value.
- The `name` prop has been added to the input element.

### src/inputs/TextArea/TextArea.tsx
- The `onChange` function now receives the event object instead of a string value.
- The `name` prop has been added to the textarea element.

### src/inputs/TextInput/TextInput.tsx
- The `onChange` function now receives the event object instead of a string value.
- The `name` prop has been added to the input element.

### src/validation/FormValidation.scss
- Styles for error messages have been added.

### src/validation/FormValidation.tsx
- A new file `FormValidation.tsx` has been added.
- The `validate` function has been implemented to validate the form values based on the task requirements.

Overall, the code changes cover the task requirements by implementing form validation and displaying error messages for each required field. The form context is used to manage the form state and handle form submission. The code changes adhere to the provided task requirements and make the necessary updates to achieve the desired functionality.

2023-07-11 20:46 UTC, Sumick requested changes
We are missing `touched` here, so it validates after submitting. You will also find a suggestion of how to handle this error messages

2023-07-11 20:46 UTC, Sumick commented on src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
> +            <p>{errors.city as string}</p>
**nitpick:** We should not do type casting. What you will probably need to do is:

```jsx
{errors?.city && touched?.city &&  <p>{errors.city}</p>}
```

2023-07-12 23:33 UTC, Sumick requested changes
You basically did what Formik has already production ready: https://formik.org/docs/api/useFormikContext - I mentioned about it in the context of why do we select this specific library :D We need to refactor this first - maybe it will help solve your other issues

2023-07-12 23:33 UTC, Sumick commented on src/contexts/FormContext.tsx
> +export const FormProvider: React.FC<{ children: React.ReactNode }> = ({
**issue:** But why? Formik has it out of the box: https://formik.org/docs/api/useFormikContext

2023-07-14 15:29 UTC, Sumick requested changes
We need few improvements. In terms of Checkboxes, ensure that all checkboxes are matching with their `labels`. I noticed that they are missing `htmlFor` attribute. Compare with Nerdux one if you need

2023-07-14 15:29 UTC, Sumick commented on src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
> +          <div className={errors.city ? styles.errorMsg : ''}>
**nitpick:** We were talking about making `InputWrapper` component for these, so it displays errors, and keep our inputs packed

2023-07-14 15:29 UTC, Sumick commented on src/inputs/Checkbox/Checkbox.tsx
>      <label className={styles.checkboxLabel}>
**issue:** label is missing `htmlFor`, it can be the issue why validation works incorrectly

2023-07-14 15:29 UTC, Sumick commented on src/services/CreateProfileFormService.ts
> +import { useFormik } from 'formik'
**nitpick:** it's not a components, so this file should be named in camelCase, `createProfileForm.ts` (no need to add Service, as it's in `services` directory

2023-07-17 12:23 UTC, Sumick approved these changes
Looks good - Im leaving one non-blocking nitpick

2023-07-17 12:23 UTC, Sumick commented on src/components/CreateProfile/LocationPreferences/LocationPreferences.tsx
> +          <CreateProfileFormError error={errors.country}>
**nitpick:** Why `CreateProfileFormError` not `FormInputError`? I think it should be more generic, as it could be used in other parts of the system

2023-07-17 12:36 UTC, mimakuch approved these changes

2023-07-17 12:36 UTC, merged