Feat/profile mobile user interface
nerdbord/good-dev-hunting-app pull request #49
Opened 2023-08-13 22:53 UTC by Wiecek-K

2023-08-13 23:41 UTC, NerdbordMentor requested changes
Based on the provided task requirements and code changes, here is the code review:

1. **app/(profile)/my-profile/page.module.scss**: The changes in this file seem to be in line with the task requirements. The padding for mobile devices has been set to 0 which should help with the display on smaller screens.

2. **next.config.js**: The addition of 'sm.ign.com' to the list of image domains doesn't seem to be directly related to the task requirements. However, it doesn't contradict them either.

3. **src/backend/user/user.serializer.ts**: Commenting out the image property in the serialized user data could potentially cause issues if other parts of the application rely on this data. This change doesn't seem to be in line with the task requirements.

4. **src/components/CopyEmail/CopyEmail.module.scss**: The changes in this file should help improve the display of the CopyEmail component on mobile devices, which is in line with the task requirements.

5. **src/components/Headers/MyProfileHeader/MyProfileHeader.module.scss**: The changes in this file should help improve the display of the MyProfileHeader component on mobile devices, which is in line with the task requirements.

6. **src/components/MyProfile/ProfileDetails/ProfileDetails.module.scss**: The changes in this file should help improve the display of the ProfileDetails component on mobile devices, which is in line with the task requirements.

7. **src/components/MyProfile/ProfileDetails/ProfileDetails.tsx**: The hardcoded values for tech stack and bio are not in line with the task requirements. The data should be fetched from a backend or at least be dynamic.

8. **src/components/MyProfile/ProfileMain/ProfileMain.module.scss**: The changes in this file should help improve the display of the ProfileMain component on mobile devices, which is in line with the task requirements.

9. **src/components/MyProfile/ProfileMain/ProfileMain.tsx**: Similar to ProfileDetails.tsx, there are hardcoded values here that are not in line with the task requirements. The data should be fetched from a backend or at least be dynamic.

10. **src/components/MyProfile/ProfileMain/avatar-generations_prsz.jpg**: This file was added but it's not clear from the task requirements if a new avatar image was needed.

11. **src/inputs/LogOutBtn/LogOutBtn.module.scss**: The changes in this file should help improve the display of the LogOutBtn component on mobile devices, which is in line with the task requirements.

12. **src/utils/styleVariables.scss**: This file was added and it contains useful mixins for handling different screen sizes, which is in line with the task requirements.

In conclusion, most of the changes are in line with the task requirements of adjusting the Profile UI for mobile devices. However, there are some hardcoded values that need to be addressed.

2023-08-14 12:13 UTC, wawrzonnn commented on src/utils/styleVariables.scss
> +}
We have a globals.scss file, that's where these mixins should be

2023-08-14 12:14 UTC, wawrzonnn commented on src/components/MyProfile/ProfileMain/avatar-generations_prsz.jpg
This should be in the src/assets/images

2023-08-14 18:44 UTC, Sumick requested changes
I don't understand why did we reverted dynamic values to hardcoded ones here - if you needed them to set proper layout, I suggest you to mock profile, or create one

2023-08-14 18:44 UTC, Sumick commented on src/backend/user/user.serializer.ts
> +      // image: data.githubDetails?.image,
**nitpick**: This can be removed

2023-08-14 18:44 UTC, Sumick commented on src/components/MyProfile/ProfileMain/ProfileMain.tsx
> +              src="https://sm.ign.com/ign_nordic/cover/a/avatar-gen/avatar-generations_prsz.jpg"
**nitpick:** Why?

2023-08-15 09:02 UTC, Wiecek-K commented on src/components/MyProfile/ProfileMain/ProfileMain.module.scss
> +
![image](https://github.com/nerdbord/good-dev-hunting-app/assets/113645679/e55963ac-d13d-4da8-b456-a0260feefc2a)
I can't completely remove the imports.
I have to change them to global file path

2023-08-17 10:20 UTC, closed without merging