Feat/my profile mobile user interface
nerdbord/good-dev-hunting-app pull request #52
Opened 2023-08-17 10:23 UTC by Wiecek-K

2023-08-17 10:24 UTC, NerdbordMentor requested changes
Based on the provided task requirements and the code changes, it seems that the code changes are in line with the task requirements. The task was to adjust the "My profile UI" to be able to display on mobile devices. The code changes show that various CSS classes have been modified with mobile-specific styles using the `@include mobile` mixin, which is defined in `src/styles/mixins.scss`.

The changes in `next.config.js` seem unrelated to the task requirements, as they only add a new domain for images. However, this does not conflict with the task requirements.

The changes in `src/components/MyProfile/ProfileDetails/ProfileDetails.tsx` seem to replace a dynamic profile description with a hardcoded one. This might be a placeholder for testing, but it should be noted that in a final version this should be replaced back to a dynamic value.

In conclusion, the code changes seem to cover the task requirements of making the profile UI mobile responsive. However, please ensure that any hardcoded values are only for testing and will be replaced with dynamic values in the final version.

2023-08-17 10:41 UTC, NerdbordMentor approved these changes
Based on the provided task requirements and code changes, it appears that the changes are in line with the goal of adjusting the "My Profile UI" for display on mobile devices. The developer has made use of a mobile mixin to apply styles specifically for mobile viewports. 

Here's a breakdown of the changes:

1. **app/(profile)/my-profile/page.module.scss**: Padding for the wrapper class has been adjusted for mobile screens.

2. **src/components/CopyEmail/CopyEmail.module.scss**: Padding and white-space properties have been adjusted for mobile screens.

3. **src/components/Headers/MyProfileHeader/MyProfileHeader.module.scss**: Various adjustments have been made to accommodate mobile screens, including changes to flex-direction, padding, font-size, and image dimensions.

4. **src/components/MyProfile/ProfileDetails/ProfileDetails.module.scss**: Several adjustments have been made for mobile screens, including changes to padding, margin, and display properties.

5. **src/components/MyProfile/ProfileMain/ProfileMain.module.scss**: Numerous adjustments have been made for mobile screens, including changes to padding, position, display properties, and scrollbar styling.

6. **src/components/MyProfile/ProfileMain/ProfileMain.tsx**: The social media links have been moved within the addInfoBox div for mobile screens.

7. **src/components/MyProfile/ProfileTopBar/ProfileTopBar.module.scss**: Padding and position properties have been adjusted for mobile screens.

8. **src/inputs/Button/Button.module.scss**: Width and padding properties have been adjusted for mobile screens.

9. **src/inputs/LogOutBtn/LogOutBtn.module.scss**: Margin property has been adjusted for mobile screens.

10. **src/styles/mixins.scss**: This new file has been added to define mixins for mobile and desktop media queries.

Without the actual design link or screenshots, it's impossible to verify if the UI implementation is as close as possible to the provided design. However, based on the code changes, it appears that the developer has made a significant effort to make the "My Profile UI" responsive for mobile devices.

2023-08-17 15:51 UTC, wawrzonnn approved these changes

2023-08-19 06:15 UTC, wawrzonnn approved these changes

2023-08-19 11:26 UTC, AniaPiWo approved these changes

2023-08-19 11:34 UTC, Sumick approved these changes

2023-08-19 11:40 UTC, merged