feat: added toggle publish profile button
nerdbord/good-dev-hunting-app pull request #58
Opened 2023-09-06 15:24 UTC by wawrzonnn

2023-09-06 15:25 UTC, NerdbordMentor requested changes
## Code Review Report

### Task goal
The task was to enable toggling of the `isPublished` profile state by clicking on a button.

### Requirements
1. Clicking on "Publish profile" button should send an API request to the backend, and set `isPublished` to true.
2. It should display a confirmation popup when the profile is unpublished or published.
3. The below endpoint should be used:
```
curl -X POST \
  http://localhost:3000/api/profiles/:id/publish \
  -H 'Content-Type: application/json' \
  -d '{
    "isPublished": true | false
}'
```

### Code Review

#### app/(profile)/my-profile/page.tsx
The changes in this file cover the requirement of sending an API request to the backend. The `getProfileByUserEmail` function is used to get the profile ID which is then passed as a prop to the `ProfileTopBar` component.

#### app/api/profiles/[id]/publish/route.ts
The changes in this file cover the requirement of toggling the `isPublished` state. The `getProfileById` function is used to get the existing profile and then the `isPublished` state is toggled using the `updateUserData` function.

#### src/components/MyProfile/ProfileTopBar/ProfileTopBar.tsx
The changes in this file cover the requirement of sending an API request to the backend and toggling the `isPublished` state. The `handleTogglePublish` function is used to toggle the `isPublished` state and update it in the component's state. However, there is no code for displaying a confirmation popup when the profile is unpublished or published, which is one of the requirements.

#### src/lib/apiClient.ts
The changes in this file cover the requirement of sending an API request to the backend. The `togglePublishMyProfile` function sends a POST request to the `/profiles/:id/publish` endpoint.

#### src/lib/auth.ts
The changes in this file remove the `profileId` from the session token. This change does not seem to be related to the task requirements.

#### src/styles/_mixins.scss
This file was added and contains two media query mixins for mobile and desktop. This change does not seem to be related to the task requirements.

### Summary
The code changes cover most of the task requirements. However, there is no code for displaying a confirmation popup when the profile is unpublished or published, which is one of the requirements. Also, there are some changes that do not seem to be related to the task requirements.

2023-10-02 16:52 UTC, Sumick approved these changes

2023-10-02 17:30 UTC, hansac91 approved these changes

2023-10-03 14:46 UTC, Sumick approved these changes

2023-10-03 15:15 UTC, merged