Feat/Move-profile-fetching-to-the-server
nerdbord/good-dev-hunting-app pull request #59
Opened 2023-09-11 11:03 UTC by AniaPiWo

2023-09-11 11:12 UTC, wawrzonnn approved these changes

2023-09-11 11:25 UTC, hansac91 approved these changes

2023-09-11 12:34 UTC, Sumick requested changes
We need to remove profileId from session, as we talked about it during call. So we have to get this other way there in the component.

2023-09-11 12:34 UTC, Sumick commented on src/components/Headers/MyProfileHeader/MyProfileHeader.tsx
> +type SessionType = {
**nitpick:** We have declared this type already - it's in next-auth.d.ts

2023-09-11 12:34 UTC, Sumick commented on src/components/Headers/DefaultHeader/DefaultHeader.tsx
> +const DefaultHeader = ({ session }: DefaultHeaderProps) => {
**nitpick:** Why passing down this session as prop and not `getServerSession` here in this component directly?

2023-09-11 12:34 UTC, Sumick commented on src/components/Headers/DefaultHeader/DefaultHeader.tsx
> +    profileId: string | null
**nitpick:** This `profileId` has to be removed from session

2023-09-11 12:34 UTC, Sumick commented on app/page.tsx
> +      <DefaultHeader session={session} />
**nitpick:** It won't work when getServerSession is called directly?

2023-09-12 10:54 UTC, Sumick requested changes
We were supposed to remove profileId from session, not exchange it for whole `profile` object. We can't have profile data in session as there is possibility that it will be null even when user will have profile. We have to remove all profile details from token and session

2023-09-12 10:54 UTC, Sumick commented on src/lib/auth.ts
> +      token.profile = !!foundUser.profile
**issue:** But we had to remove `profileId` from session because it leads to critical bug. Adding `profile` to session is basically the same problem

2023-09-12 10:54 UTC, Sumick commented on src/lib/auth.ts
> +        session.user.profile = token.profile as boolean
**issue:** You did basically the same what you removed :P

2023-09-12 10:54 UTC, Sumick commented on types/next-auth.d.ts
> +      profile: Profile | null
**issue:** But why? You exchanged profileId for profile which is the same

2023-09-13 16:32 UTC, Sumick approved these changes
Looks good! Please fix type name before merging

2023-09-14 10:58 UTC, merged