feat: added publish profile confirmation popup
nerdbord/good-dev-hunting-app pull request #64
Opened 2023-10-03 18:49 UTC by wawrzonnn

2023-10-03 19:21 UTC, hansac91 approved these changes

2023-10-04 09:28 UTC, mmcode9407 requested changes
![image](https://github.com/nerdbord/good-dev-hunting-app/assets/108949945/7da1529c-5a4d-4c9e-bf26-7aebdc5fb4b2)
The popup is a bit transparent but I don't see the css property responsible for it. Is this problem only with me?

2023-10-04 09:28 UTC, mmcode9407 commented on src/components/TogglePublishPopup/TogglePublishPopup.module.scss
> +  border-radius: 10px;
you use `border-radius` second time below

2023-10-04 09:28 UTC, mmcode9407 commented on src/components/TogglePublishPopup/TogglePublishPopup.module.scss
> +  border-radius: 5px;
here

2023-10-04 20:24 UTC, mmcode9407 approved these changes
Nice! Just delete unused imports and props in `ProfileTopBar` before you merge :)

2023-10-04 20:57 UTC, Sumick approved these changes

2023-10-04 21:09 UTC, merged