feat: added user profile github link
nerdbord/good-dev-hunting-app pull request #71
Opened 2023-10-06 16:54 UTC by wawrzonnn

2023-10-06 19:53 UTC, hansac91 approved these changes

2023-10-06 20:00 UTC, Sumick requested changes
User, and Profile relate to each other. You dont need to query them separately. You can include them in each other, and get from DB as a single record.

2023-10-07 14:01 UTC, Sumick commented on src/data/frontend/user/types.ts
> +    username: string | null
**nitpick:** username cannot be null when GighubDetails is created

2023-10-12 11:33 UTC, Sumick approved these changes
Looks good!

2023-10-12 11:36 UTC, darionauta approved these changes
OK

2023-10-12 15:53 UTC, merged