feat: user roles setup
nerdbord/good-dev-hunting-app pull request #72
Opened 2023-10-06 19:28 UTC by darionauta

2023-10-06 19:30 UTC, wawrzonnn approved these changes

2023-10-06 19:37 UTC, Sumick requested changes
We should not add `role` to Profile, but to User. User can exist without Profile, and role should be always present for User, no matter if User has profile or not.

2023-10-06 19:53 UTC, hansac91 approved these changes

2023-10-07 20:24 UTC, Sumick requested changes
These are still old changes. `role` is part of Profile, and should be part of User. Btw, can we set `roles` instead of role, so it's possible to hold array of roles instead of one? It will be more proper solution.

2023-10-07 21:03 UTC, Sumick approved these changes
Looks good!

2023-10-07 21:04 UTC, merged