Feat/setup dashboard cms
nerdbord/good-dev-hunting-app pull request #74
Opened 2023-10-13 07:11 UTC by mmcode9407

2023-10-13 07:50 UTC, wawrzonnn approved these changes
Good job! I think it's time to introduce global styles for our headers. We have several common classes like .wrapper, .headerContent, .logo, .title, and .frameButtons that we use in every header. It might be beneficial to consolidate them.

2023-10-13 08:16 UTC, darionauta approved these changes

2023-10-13 08:16 UTC, darionauta commented on src/components/Headers/DashboardHeader/DashboardHeader.tsx
> +  const profile = session
I wonder if we could shorten this code a bit?
For example:
`const profile = session && await findUserByEmail(session.user.email)`
`if(!profile || !profile?.roles.includes(Role.MODERATOR)) redirect(AppRoutes.home)`

2023-10-13 12:12 UTC, Sumick requested changes
We need to move RootLayout to the root of `app` dir, based on documentation. HTML, body tag, and fonts should be declared only once there. https://nextjs.org/docs/app/api-reference/file-conventions/layout

Then we should create DashboardLayout component, which holds only DashboardHeader, Container, and Children. `AuthProvider` can be in RootLayout

2023-10-13 12:12 UTC, Sumick commented on app/(moderation)/dashboard/layout.tsx
> +      <body className={ibm.className}>
**nitpick:** This should not be a root layout, I will explain it in review summary

2023-10-16 20:42 UTC, Sumick approved these changes
Looks really nice now! Good job 🙌

2023-10-17 11:46 UTC, merged