Fix/fixing header
nerdbord/good-dev-hunting-app pull request #77
Opened 2023-10-18 10:58 UTC by mmcode9407

2023-10-18 11:02 UTC, hansac91 approved these changes

2023-10-18 11:06 UTC, wawrzonnn approved these changes
GJ

2023-10-20 13:10 UTC, Sumick requested changes
Looks good, we need one important fix

2023-10-20 13:10 UTC, Sumick commented on src/components/CreateProfileBtn/CreateProfileBtn.tsx
> +      })
**issue:** user can be logged in without profile. we should `router.push` to create profile page, when user is logged in but does not have profile

2023-10-20 19:40 UTC, Sumick approved these changes
👌

2023-10-20 20:47 UTC, merged