feat: added user photo uploader
nerdbord/good-dev-hunting-app pull request #79
Opened 2023-10-18 22:20 UTC by wawrzonnn

2023-10-19 21:37 UTC, hansac91 requested changes
doesn't work, Please fix it 🙂

2023-10-29 18:07 UTC, hansac91 approved these changes

2023-10-30 15:58 UTC, mmcode9407 reviewed
When I import my picture, and then (without saving) I import picture from GH, and then (without saving) I want to change picture on the same as before importing from GH, I cannot do it.

2023-10-30 15:58 UTC, mmcode9407 commented on src/components/UserPhotoUploader/UserPhotoUploader.tsx
> +    if (file) {
we should check if the file is an image also. I think we shouldn't accept other files here

2023-10-30 15:58 UTC, mmcode9407 commented on src/components/UserPhotoUploader/UserPhotoUploader.tsx
> +        setShowErrorMessage(false)
Even if we get an error it still rediretcs us on /my-profile page.

2023-10-30 15:58 UTC, mmcode9407 commented on src/components/UserPhotoUploader/UserPhotoUploader.tsx
> +              Import from Github
I think it will be good to show some loading state when upload image from github.

2023-10-30 16:22 UTC, wawrzonnn commented
> When I import my picture, and then (without saving) I import picture from GH, and then (without saving) I want to change picture on the same as before importing from GH, I cannot do it.

This component is only for people who are really determined to change their picture

2023-10-31 10:18 UTC, Sumick requested changes
Starting to look good - we need few improvements

2023-10-31 10:18 UTC, Sumick commented on app/api/files/route.ts
> +) // 7-character random string
**praise:** This will be very useful endpoint!

2023-10-31 10:18 UTC, Sumick commented on app/api/files/route.ts
> +const nanoid = customAlphabet(
**question:** Why customAlphabet instead of calling `nanoid()`?

2023-10-31 10:18 UTC, Sumick commented on app/api/user/avatar/route.ts
> +    console.log('Handling PUT request for user avatar...');
**nitpick:** Log to remove

2023-10-31 10:18 UTC, Sumick commented on app/api/user/avatar/route.ts
> +    console.log('Updated user data:', updatedUser);
nitpick: Log to remove

2023-10-31 10:18 UTC, Sumick commented on app/api/user/avatar/route.ts
> +    console.log('Found user data:', user);
nitpick: Log to remove

2023-10-31 10:18 UTC, Sumick commented on app/api/user/avatar/route.ts
> +    return new NextResponse(
**nitpick:** Let's do NextResponse.json() now as it works for you

2023-10-31 10:18 UTC, Sumick commented on src/components/CreateProfile/CreateProfileTopBar/CreateProfileTopBar.tsx
> +      // if (uploadSuccess) {
**nitpick:** Comments to remove

2023-10-31 10:18 UTC, Sumick commented on src/components/UserPhotoUploader/UserPhotoUploader.module.scss
> +font-size: 14px;
**nitpick:** Missing formatting

2023-10-31 10:18 UTC, Sumick commented on app/api/files/route.ts
> +  const contentType = req.headers.get('content-type') || 'text/plain'
**nitpick:** We should validate file types so nothing else is being uploaded. Let's create some collection of available content types. For now we should be able to upload only images

2023-10-31 10:18 UTC, Sumick commented on src/components/UserPhotoUploader/UserPhotoUploader.tsx
> +        `http://github.com/${profile?.githubUsername}.png`,
**nitpick:** should be `https`

2023-10-31 10:18 UTC, Sumick commented on src/components/UserPhotoUploader/UserPhotoUploader.tsx
> +        console.log('Uploaded file URL:', url);
**nitpick:** log to remove

2023-10-31 10:18 UTC, Sumick commented on src/contexts/UploadContext.tsx
> +  triggerUpload: boolean
**nitpick:** `isUploadTriggered`

2023-10-31 10:18 UTC, Sumick commented on src/contexts/UploadContext.tsx
> +  setTriggerUpload: React.Dispatch<React.SetStateAction<boolean>>
**nitpick:** It should start uploading instead of just toggling boolean. It's worth to pack all uploading logic inside this provider.

2023-10-31 10:18 UTC, Sumick commented on src/contexts/UploadContext.tsx
> +
**nitpick:** Let's add uploading logic to this provider here, so you just extract upload method and use it anywhere you want

2023-11-09 20:40 UTC, mmcode9407 approved these changes
Amazing job!

2023-11-18 14:48 UTC, Sumick approved these changes
Looks good! Let's clean this PR from unecesary logs before merging

2023-11-18 14:48 UTC, Sumick commented on src/components/CreateProfile/CreateProfileTopBar/CreateProfileTopBar.tsx
> +      if (Object.keys(errors).length === 0) {
**nitpick:** You can use `isValid` from `useFormikContext` instead of this

2023-11-18 14:48 UTC, Sumick commented on src/lib/auth.ts
> +  console.log('Session:', session)
**nitpick:** Log to remove

2023-11-23 14:02 UTC, merged