Feat/implement user search in cms
nerdbord/good-dev-hunting-app pull request #84
Opened 2023-10-29 13:42 UTC by mmcode9407

2023-10-29 16:29 UTC, Sumick requested changes
Mostly looks good! We need few improvements

2023-10-29 16:29 UTC, Sumick commented on src/components/FilterTabs/Tabs.tsx
> +    setActiveTab && setActiveTab(PublishingState[tab])
**nitpick:** There should not be case when such handler is undefined. We should throw error from `useMorderationFilter` when context is not found

2023-10-29 16:29 UTC, Sumick commented on src/components/FilterTabs/Tabs.tsx
> +    setEmailSearchValue && setEmailSearchValue('')
**nitpick:** Then we should remove these `ifs`

2023-10-29 16:29 UTC, Sumick commented on src/components/ModerationSearchProfile/SearchSuggestionItem.tsx
> +      <img
**nitpick:** We should use Image from `next/image` when possible

2023-10-29 16:29 UTC, Sumick commented on src/components/ProfileList/ModerationProfilesWithFilter.tsx
>    data: ProfileModel[]
**nitpick:** should be `profiles` not `data`, as it's not too descriptive

2023-10-29 16:29 UTC, Sumick commented on src/components/ProfileList/ModerationProfilesWithFilter.tsx
> +    return user?.state === publishingStateFilter
**nitpick:** Why it can be optional?

2023-10-29 16:29 UTC, Sumick commented on src/components/ProfileList/ModerationProfilesWithFilter.tsx
> +            profile && (
**nitpick:** why `if`? Filtered profiles should be truthy values

2023-10-29 16:29 UTC, Sumick commented on src/components/SearchResultsInfo/SearchResultsInfo.tsx
> +  filteredData: ProfileModel[]
**nitpick:** filteredData -> `profiles`

2023-10-29 16:29 UTC, Sumick commented on src/components/SearchResultsInfo/SearchResultsInfo.tsx
> +          <p className={styles.searchInfo}>
**nitpick:** It's a almost the same code - it can be a single component differed by some text prop

2023-10-29 16:30 UTC, wawrzonnn requested changes
a few suggestions

2023-10-29 16:30 UTC, wawrzonnn commented on src/components/SearchResultsInfo/SearchResultsInfo.tsx
> +}
We adhere to the DRY(Don't Repeat Yourself) principle, so you can simply use:
 "const isSearchActive = searchEmailValue !== '';" 
 
 and then conditionally render the classes: 
 "{isSearchActive && (
      <div className={styles[filteredData.length > 0 ? 'searchInfoCont' : 'searchEmptyInfoCont']}>..."
      
      By doing this, the code is halved in length

2023-10-29 16:30 UTC, wawrzonnn commented on src/components/ModerationSearchProfile/SearchSuggestionItem.module.scss
> +    }
Should we add cursor pointer here? :D

2023-10-29 17:19 UTC, wawrzonnn approved these changes

2023-10-30 22:28 UTC, wawrzonnn approved these changes
GJ

2023-10-30 22:28 UTC, wawrzonnn commented on src/components/ProfileList/ModerationProfileListItem.tsx
> +  profile,
https://medium.com/raccoons-group/why-you-probably-shouldnt-use-react-fc-to-type-your-react-components-37ca1243dd13

2023-10-30 22:28 UTC, wawrzonnn commented on src/components/ProfileList/ModerationProfilesWithFilter.tsx
> +            text="Search results for"
You don't need a variable and two components here, you can use:
text={filteredProfiles.length ? "Search results for" : "No search results for"}

2023-10-31 10:05 UTC, Sumick approved these changes
Looks good!

2023-10-31 10:18 UTC, darionauta approved these changes

2023-11-01 18:26 UTC, merged