Feat/implement profile state management
nerdbord/good-dev-hunting-app pull request #85
Opened 2023-10-31 23:30 UTC by darionauta

2023-11-01 13:46 UTC, Sumick requested changes
Code looks great! I found an issue in Toast Provider, we are missing toast queueing - currently they will overwrite themselves when called one by one

2023-11-01 13:46 UTC, Sumick commented on app/api/profiles/[id]/reject/route.ts
> +  if (!user || !user?.roles.includes(Role.MODERATOR)) {
**nitpick:** As this check is gonna be used frequently, we can move it to some `utils/auth` function, like:

```ts
requireUserRoles([Role.Moderator])
```

2023-11-01 13:46 UTC, Sumick commented on app/api/profiles/[id]/state/route.ts
> +  if (!user || !user?.roles.includes(Role.MODERATOR)) {
**nitpick:** we could reuse role check here

2023-11-01 13:46 UTC, Sumick commented on src/contexts/ToastContext.tsx
> +  const [toastStatus, setToastStatus] = useState<ToastStatus>(
**issue:** This toaster is missing queueing - toasts should stack. Currently they will overwrite themselves

2023-11-01 13:46 UTC, Sumick commented on src/contexts/ModalContext.tsx
> +      {children}
**nitpick:** I would suggest considering using React.portal here to render modal. It will prevent uneccessary rerenders

2023-11-02 18:22 UTC, wawrzonnn approved these changes
GJ

2023-11-02 18:39 UTC, mmcode9407 approved these changes
GJ!

2023-11-02 20:05 UTC, Sumick requested changes
Almost there! We need last improvements in modals logic

2023-11-02 20:05 UTC, Sumick commented on src/contexts/ModalContext.tsx
> +  showRejectModal: boolean
**nitpick:** I think we should only have (of course we we assume that only one modal can be visible at the time, but let's leave it for now:

```ts
export type ModalContextType = {
  isModalVisible: boolean;
  showModal: (state: boolean) => void
}
```

2023-11-02 20:05 UTC, Sumick commented on app/(moderation)/layout.tsx
> +      <RejectingReason />
**nitpick:** Currently we don't know how and where this modal is being called. We should place it where we call it.

2023-11-02 20:05 UTC, Sumick commented on src/components/ProfileList/ModerationProfileListItem.tsx
> +  const { setProfileId, setShowRejectModal } = useModal()
**nitpick:** Instead of keeping profile id in modal provider, just render this Reject Modal here, and pass `profileId` as prop.

2023-11-02 21:24 UTC, Sumick approved these changes
Looks great! Awesome job 🔥👏

2023-11-02 22:29 UTC, merged