Feat/profile form UI fixes
nerdbord/good-dev-hunting-app pull request #96
Opened 2023-11-30 18:16 UTC by AniaPiWo

2023-11-30 21:58 UTC, hansac91 approved these changes

2023-11-30 23:17 UTC, wawrzonnn approved these changes
![FB_IMG_1700672571039](https://github.com/nerdbord/good-dev-hunting-app/assets/104648914/46bb62bf-27a4-4ee1-a395-3cde3ff3c299)

2023-12-01 19:27 UTC, Sumick requested changes
We should fix this Loader to not duplicate it every time - it should be some one component, and then reused

2023-12-01 19:27 UTC, Sumick commented on app/(profiles)/my-profile/create/loading.tsx
> +const Loading = () => {
**nitpick:** I think we should reuse this loader, not duplicate it

2023-12-01 20:01 UTC, Sumick approved these changes
🔥🔥🔥

2023-12-02 10:07 UTC, merged