Feat/update country selection
nerdbord/good-dev-hunting-app pull request #98
Opened 2023-12-07 14:43 UTC by CharlesSquirel

2023-12-08 13:17 UTC, Sumick requested changes
UI looks good, but it does not work correctly yet - we need few improvements, but you are really close! Good job!

2023-12-08 13:17 UTC, Sumick commented on src/components/TextInputWithDropdown/TextInputWithDropdown.tsx
> +      {values.country.length !== 0 && isDropdownActive && (
**issue:** `isDropdownActive` prevents it from working here

2023-12-08 13:17 UTC, Sumick commented on src/components/TextInputWithDropdown/TextInputWithDropdown.tsx
> +      onClick={(e) => handleCountryInputClick(e)}
**issue:** item selection should happen in DropdownCountry, as `onSelect`

2023-12-08 13:17 UTC, Sumick commented on src/components/TextInputWithDropdown/TextInputWithDropdown.tsx
> +    const isTargetInput = (e.target as HTMLElement).tagName === 'INPUT'
**nitpick:** This is too hacky - we can do it without this function

2023-12-08 13:17 UTC, Sumick commented on src/components/TextInputWithDropdown/TextInputWithDropdown.tsx
> +        <DropdownCountry
**nitpick:** Dropdown should close after selection

2023-12-14 18:43 UTC, Sumick approved these changes
Looks good, great job! Let's add `useOutsideClick` hook before merging

2023-12-14 18:43 UTC, Sumick commented on src/components/TextInputWithDropdown/TextInputWithDropdown.tsx
> +  useEffect(() => {
**nitpick:** We should create some reusable hook called `useOutsideClick` so its possible to use it somewhere else

2023-12-14 19:08 UTC, mmcode9407 approved these changes
Nice!

2023-12-14 22:42 UTC, wawrzonnn approved these changes
Great job! a lot of hard work has gone into this

2023-12-15 07:52 UTC, merged